build: false

platform:
    - x64

image:
    - Visual Studio 2015
    - Visual Studio 2017
    - Visual Studio 2019

environment:
  matrix:
    - CONDA: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      CONDA_ARCH: "64"
      PACKAGE_SUFFIX: "cp37-cp37m"
    - CONDA: "C:\\Miniconda38-x64"
      PYTHON_VERSION: "3.8"
      CONDA_ARCH: "64"
      PACKAGE_SUFFIX: "cp38-cp38m"

init:
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" set VCARGUMENT=%PLATFORM%
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2019" set VCVARPATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
    - echo "%VCVARPATH% %VCARGUMENT%"
    - "%VCVARPATH% %VCARGUMENT%"
    - SET PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%CONDA%\bin;%PATH%
    - conda info
    - python --version

matrix:
    fast_finish: true
    # Miniconda38 is not available on Visual Studio 2015 & 2017 images
    exclude:
        - image: Visual Studio 2015
          CONDA: "C:\\Miniconda38-x64"
        - image: Visual Studio 2017
          CONDA: "C:\\Miniconda38-x64"

install:
    - conda create --yes -n build_env python=%PYTHON_VERSION%
    - activate build_env
    - conda install cmake perl nasm scikit-build=0.10.0 -y -c conda-forge

build_script:
    - pip wheel --verbose .
    - ls *.whl

test_script:

    # create test env
    - conda create --yes -n test_env python=%PYTHON_VERSION% nose
    - activate test_env
    - conda install pytest nbval -y -c conda-forge

    # install from wheel
    - pip install xeus-robot --no-index -f .

    # run tests from install wheel
    - cd test
    - pytest . -v

artifacts:
   - path: 'xeus_robot-*.whl'  # find produced xeus_robot wheels

deploy:
    release: Draft
    provider: GitHub
    auth_token:
      secure: oa2Ksc6kYvGfTbxpcvm2FZHP1kknFvQqve7lavJKEkpJW1prEvLnrZipb4SXlMVK
    artifact: /xeus_robot.*\.whl/
    draft: true
    on:
      branch: master                 # release from master branch only
    force_update: true
